### ISSUE TITLE
Can't seem to work over https

### ISSUE THREAD

**Issue by zooshme** [rill-js/fetcher#1]
I've got fetcher integrated with horizon.io and I would like to use both over https but fetcher doesn't seem to like https. I'm getting an error 

`Protocol "https:" not supported. Expected "http:"`

**Comment by DylanPiercey** [comment]
This is because the module uses "agentkeepalive" which boosts performance a lot in cases where you are calling the same server isomorphically.

As of https://github.com/rill-js/fetcher/commit/15983e7ad94a7b478e6a2e5b825586698febc36f I have added the "keepAlive" option which is off by default so this should now work for you.

If you would like to continue using keep alive but also use https you can configure this module with the following:

```js
var HttpsAgent = require('agentkeepalive').HttpsAgent;

app.use(fetcher({
    agent: new HttpsAgent()
})
```

**Comment by zooshme** [comment]
Thank you for your prompt reply. I have added the httpsAgent to fetcher middleware but I still seem to get the same error. I've looked at your example for using fetcher and it has a 'browser' field in the package.json which points to an empty file 'noop.js'. I'm not quite what I should include in a file like this. I'm familiar with the idea of writing isomorphic code from Meteor and I presume is-browser does the same thing like Meteor.isClient() method. But where would I use it in this case?

**Comment by DylanPiercey** [comment]
@zooshme Are you using browserify? If so with is-browser you can do:

```js
app.use(fetcher({
    agent: !process.browser && new require('agentkeepalive')()
})
```

Feel free to shoot me a message in the [gitter](https://gitter.im/rill-js/rill) for faster responses 👍.

**Comment by DylanPiercey** [comment]
I also created a pr [here](https://github.com/node-modules/agentkeepalive/pull/39) which would allow for isomorphic use of "agentkeepalive" and it would just require a noop in the browser. (Similar to my noop shim but also with the "HttpsAgent".

This would allow for the simpler example I posted earlier without having to shim anything yourself.

```js
var HttpsAgent = require('agentkeepalive').HttpsAgent;

app.use(fetcher({
    agent: new HttpsAgent()
})
```
